### ISSUE TITLE
TreeTreeTest_expire_Test crash

### ISSUE THREAD

**Issue by tigerzhang** [TigerZhang/logcabin#10]
```
(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:66
#1  0x0000000000483984 in __gthread_mutex_lock (__mutex=0xb8) at /usr/include/x86_64-linux-gnu/c++/4.8/bits/gthr-default.h:748
#2  0x00000000004858dc in std::mutex::lock (this=0xb8) at /usr/include/c++/4.8/mutex:134
#3  0x000000000049e1c2 in LogCabin::Core::Mutex::lock (this=0xb8) at /home/parallels/logcabin/Core/Mutex.h:47
#4  0x00000000004a3b6b in std::unique_lock<LogCabin::Core::Mutex>::lock (this=0x7fffffffd510) at /usr/include/c++/4.8/mutex:511
#5  0x00000000004a2157 in std::unique_lock<LogCabin::Core::Mutex>::unique_lock (this=0x7fffffffd510, __m=...) at /usr/include/c++/4.8/mutex:443
#6  0x00000000004941f8 in LogCabin::Server::RaftConsensus::replicate (this=0x0, operation=...) at /home/parallels/logcabin/Server/RaftConsensus.cc:1587
#7  0x0000000000503af4 in LogCabin::Tree::Tree::appendExpireKeyEntry (this=0x7ffff2c34768, path="/a", expireAt=1505582857)
    at /home/parallels/logcabin/Tree/Tree.cc:1394
#8  0x000000000050654c in LogCabin::Tree::Tree::isKeyExpired (this=0x7ffff2c34768, path="/a") at /home/parallels/logcabin/Tree/Tree.cc:1691
#9  0x00000000005066e4 in LogCabin::Tree::Tree::read (this=0x7ffff2c34768, symbolicPath="/a", contents="")
    at /home/parallels/logcabin/Tree/Tree.cc:1705
#10 0x00000000006f88ee in LogCabin::Tree::(anonymous namespace)::TreeTreeTest_expire_Test::TestBody (this=0x7ffff2c34700)
    at /home/parallels/logcabin/Tree/TreeTest.cc:701
#11 0x000000000079f6e4 in void testing::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#12 0x000000000079ed16 in void testing::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#13 0x00000000007933e7 in testing::Test::Run() ()
#14 0x0000000000793ab4 in testing::TestInfo::Run() ()
#15 0x0000000000793ff0 in testing::TestCase::Run() ()
#16 0x0000000000798a3e in testing::internal::UnitTestImpl::RunAllTests() ()
#17 0x000000000079f819 in bool testing::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#18 0x000000000079f2a5 in bool testing::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#19 0x0000000000797837 in testing::UnitTest::Run() ()
#20 0x00000000004831c9 in main (argc=1, argv=0x7fffffffdfd8) at /home/parallels/logcabin/test/TestRunner.cc:141
```

**Comment by johnzeng** [comment]
Fixed by commit 682da23fb412a46c6d2af454f4a38eb03ac91803
